__copyright__    = 'Copyright (C) 2022 WSOFT.'
__version__      = '1.9.0'
__license__      = 'MIT'
__author__       = 'WSOFT'
__author_email__ = 'info@wsoft.ws'
__url__          = 'http://wsoft-project.github.io/lantana/'