__copyright__    = 'Copyright (C) 2022 WSOFT.'
__version__      = '2.7.6'
__license__      = 'MIT'
__author__       = 'WSOFT'
__author_email__ = 'info@wsoft.ws'
__url__          = 'https://lantana.wsoft.ws/'