#!/bin/sh

# Set up virtual environment
python3 -m venv venv
source venv/bin/activate

# Install i18n support for mkdocs
pip install 'mkdocs[i18n]'

# Building i18n support
pybabel compile --statistics --directory lantana/locales -l en
pybabel compile --statistics --directory lantana/locales -l ja

# Install this package in editable mode
pip install --use-pep517 $1 .
