name: Upload pypi package release

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install wheel
        pip install 'mkdocs[i18n]'
    - name: Build
      run: |
        . build.sh
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
